package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/daniele/gestione-caselo/backend/eventform/internal/graphql/model"
)

// SubmitEventBooking is the resolver for the submitEventBooking field.
func (r *mutationResolver) SubmitEventBooking(ctx context.Context, input model.EventBookingInput) (*model.EventBookingResponse, error) {
	// Basic validation
	if input.FullName == "" {
		return nil, fmt.Errorf("fullName is required")
	}
	if input.Email == "" {
		return nil, fmt.Errorf("email is required")
	}
	if input.Phone == "" {
		return nil, fmt.Errorf("phone is required")
	}
	if input.Description == "" {
		return nil, fmt.Errorf("description is required")
	}
	if input.Date == "" {
		return nil, fmt.Errorf("date is required")
	}
	if !input.AcceptData {
		return nil, fmt.Errorf("acceptData must be true")
	}

	// TODO: Queue email jobs for admin and customer

	return &model.EventBookingResponse{
		Success: true,
		Message: "Richiesta di prenotazione inviata con successo",
	}, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (*model.HelloResponse, error) {
	return &model.HelloResponse{
		Message: "Hello World!",
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
